plugins {
    id 'java'
    id 'org.springframework.boot' version '2.5.15'
    id 'io.spring.dependency-management' version '1.0.15.RELEASE'
    id 'jacoco'
}

group = 'com.freddiemac.infolens'
version = '1.0.0'
sourceCompatibility = '1.8'
targetCompatibility = '1.8'

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-rest'
    implementation 'org.springframework.boot:spring-boot-starter-jersey'
    implementation 'org.springframework.boot:spring-boot-devtools'
    implementation 'org.apache.tomcat.embed:tomcat-embed-core:9.0.99'

    // Cloud & Feign
    compileOnly 'org.springframework.cloud:spring-cloud-starter-openfeign:3.0.8'
    implementation 'io.github.openfeign:feign-okhttp:13.1'

    // Security
    implementation 'org.springframework.security:spring-security-core:5.8.9'
    implementation 'org.springframework.security:spring-security-crypto:5.8.9'
    implementation 'org.springframework.security:spring-security-web:5.8.9'

    // Database
    implementation 'com.microsoft.sqlserver:mssql-jdbc:10.2.0.jre8'

    // OpenAPI / Swagger
    implementation 'io.springfox:springfox-boot-starter:3.0.0'
    implementation 'io.springfox:springfox-swagger-ui:3.0.0'
    implementation 'io.swagger.core.v3:swagger-annotations:2.1.2'
    implementation 'org.webjars:swagger-ui:5.17.14'

    // Utilities
    implementation 'org.apache.poi:poi-ooxml:5.2.3'
    implementation 'org.codehaus.janino:janino:3.1.9'
    implementation 'org.modelmapper:modelmapper:3.1.1'
    implementation 'org.yaml:snakeyaml:2.0'
    implementation 'org.springframework.hateoas:spring-hateoas:1.5.6'
    implementation 'commons-beanutils:commons-beanutils:1.10.0'
    implementation 'commons-net:commons-net:3.11.1'
    implementation 'org.apache.tika:tika-core:2.9.1'
    implementation 'com.google.guava:guava:32.0.0-jre'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.github.tomakehurst:wiremock-jre8:2.35.1'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:2.8.9'
}

test { useJUnitPlatform() }
